package com.shanbei.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.shanbei.greendao.ScallopWord;
import com.shanbei.greendao.ScallopLessonInfo;

import com.shanbei.greendao.ScallopWordDao;
import com.shanbei.greendao.ScallopLessonInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scallopWordDaoConfig;
    private final DaoConfig scallopLessonInfoDaoConfig;

    private final ScallopWordDao scallopWordDao;
    private final ScallopLessonInfoDao scallopLessonInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scallopWordDaoConfig = daoConfigMap.get(ScallopWordDao.class).clone();
        scallopWordDaoConfig.initIdentityScope(type);

        scallopLessonInfoDaoConfig = daoConfigMap.get(ScallopLessonInfoDao.class).clone();
        scallopLessonInfoDaoConfig.initIdentityScope(type);

        scallopWordDao = new ScallopWordDao(scallopWordDaoConfig, this);
        scallopLessonInfoDao = new ScallopLessonInfoDao(scallopLessonInfoDaoConfig, this);

        registerDao(ScallopWord.class, scallopWordDao);
        registerDao(ScallopLessonInfo.class, scallopLessonInfoDao);
    }
    
    public void clear() {
        scallopWordDaoConfig.getIdentityScope().clear();
        scallopLessonInfoDaoConfig.getIdentityScope().clear();
    }

    public ScallopWordDao getScallopWordDao() {
        return scallopWordDao;
    }

    public ScallopLessonInfoDao getScallopLessonInfoDao() {
        return scallopLessonInfoDao;
    }

}
