package com.shanbei.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ScallopWordCache".
 */
public class ScallopWord {

    private Long id;
    /** Not-null value. */
    private String lessonBelong;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String level;
    /** Not-null value. */
    private String info;

    public ScallopWord() {
    }

    public ScallopWord(Long id) {
        this.id = id;
    }

    public ScallopWord(Long id, String lessonBelong, String content, String level, String info) {
        this.id = id;
        this.lessonBelong = lessonBelong;
        this.content = content;
        this.level = level;
        this.info = info;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLessonBelong() {
        return lessonBelong;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLessonBelong(String lessonBelong) {
        this.lessonBelong = lessonBelong;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getLevel() {
        return level;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLevel(String level) {
        this.level = level;
    }

    /** Not-null value. */
    public String getInfo() {
        return info;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInfo(String info) {
        this.info = info;
    }

}
