package com.shanbei.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.shanbei.greendao.ScallopLessonInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ScallopLessonCache".
*/
public class ScallopLessonInfoDao extends AbstractDao<ScallopLessonInfo, Long> {

    public static final String TABLENAME = "ScallopLessonCache";

    /**
     * Properties of entity ScallopLessonInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UnitBelong = new Property(1, String.class, "UnitBelong", false, "UNIT_BELONG");
        public final static Property LessonList = new Property(2, String.class, "LessonList", false, "LESSON_LIST");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Info = new Property(5, String.class, "info", false, "INFO");
    };


    public ScallopLessonInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ScallopLessonInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ScallopLessonCache\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UNIT_BELONG\" TEXT NOT NULL ," + // 1: UnitBelong
                "\"LESSON_LIST\" TEXT NOT NULL ," + // 2: LessonList
                "\"CONTENT\" TEXT NOT NULL ," + // 3: content
                "\"TITLE\" TEXT NOT NULL ," + // 4: title
                "\"INFO\" TEXT NOT NULL );"); // 5: info
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ScallopLessonCache\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ScallopLessonInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUnitBelong());
        stmt.bindString(3, entity.getLessonList());
        stmt.bindString(4, entity.getContent());
        stmt.bindString(5, entity.getTitle());
        stmt.bindString(6, entity.getInfo());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ScallopLessonInfo readEntity(Cursor cursor, int offset) {
        ScallopLessonInfo entity = new ScallopLessonInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // UnitBelong
            cursor.getString(offset + 2), // LessonList
            cursor.getString(offset + 3), // content
            cursor.getString(offset + 4), // title
            cursor.getString(offset + 5) // info
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ScallopLessonInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUnitBelong(cursor.getString(offset + 1));
        entity.setLessonList(cursor.getString(offset + 2));
        entity.setContent(cursor.getString(offset + 3));
        entity.setTitle(cursor.getString(offset + 4));
        entity.setInfo(cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ScallopLessonInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ScallopLessonInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
